---
title: "Data Visualisation using RShiny: Day 2"
author: "2.1 - 2.3 Worksheet"
output: 
  html_document:
    theme: yeti
    highlight: tango

---
---

<style>
h1, h2, h3, h4 {font-weight: bold;}
.blue {color: #4E23B8;}
hr {border: 2px solid black;}
a.title:link {color: white; text-decoration: none;}
a.title:visited {color: white; text-decoration: none;}
a.title:hover {color: #c9bde9; text-decoration: none;}
a.title:active {color: white; text-decoration: none;}
a.main:link {color: #4E23B8; text-decoration: none;}
a.main:visited {color: #4E23B8; text-decoration: none;}
a.main:hover {color: #4E23B8; font-weight: bold; text-decoration: none;}
a.main:active {color: #4E23B8; text-decoration: none;}
.panel-aims {color: white; background-color: #4E23B8; border-top: 3px solid black; border-bottom: 3px solid black; padding-left: 15px; padding-right: 15px; } 
.panel-section {color: black; background-color: #c9bde9; border-top: 3px solid black; border-bottom: 3px solid black; padding-left: 15px; padding-right: 15px; } 
</style>

<!--- ---------------------------------------------------------------------- -->
<!--- Aims section -->

<br>
<div class="row"> <!--- Setup grid for layout -->
<div class="col-md-12"> <!--- Begin column set -->
<div class="panel panel-aims"> <!--- Begin panel -->
<h3>Contents</h3>
Click to view a specific section of the document.  
<br>

<b>2.1 &nbsp; </b> Recap Day 1 and intro to mapping in R
<ul>
<li><a class="title" href="#2.1a">2.1a Load libraries and data, prepare for mapping</a></li>
</ul>
<br>

<b>2.2 &nbsp; </b> Build a leaflet map in R
<ul>
<li><a class="title" href="#2.2a">2.2a Try some options for provider tiles</a></li>
<li><a class="title" href="#2.2b">2.2b Add circles coloured by species with legend and scale bar</a></li>
<li><a class="title" href="#2.2c">2.2c Colour points by density with a continuous colour scale</a></li>
<li><a class="title" href="#2.2d">2.2d Build choropleth with circles for point data</a></li>
<li><a class="title" href="#2.2e">2.2e Build map showing raster and shape data</a></li>
</ul>
<br>

<b>2.3 &nbsp; Build an interactive map in RShiny</b>
<ul>
<li><a class="title" href="#2.3a">2.3a Colouring points by a selected variable</a></li>
<li><a class="title" href="#2.3b">2.3b Displaying a subset of points using pickerInput</a></li>
<li><a class="title" href="#2.3c">2.3c Selectable map layers</a></li>
<li><a class="title" href="#2.3d">2.3d Adding a slider to choose the date range of points displayed</a></li>
</ul>
<br>

</div> <!--- End panel -->
</div> <!--- End column set -->
</div> <!--- End grid -->


<!--- ---------------------------------------------------------------------- -->
<!--- 2.1 Recap Day 1 and intro to mapping in R -->

<br>
<div class="row"> <!--- Setup grid for layout -->
<div class="col-md-12"> <!--- Begin column set -->
<div class="panel panel-aims"> <!--- Begin panel -->
<h3>2.1 &nbsp; Recap Day 1 and intro to mapping in R</h3>
</div> <!--- End panel -->
</div> <!--- End column set -->
</div> <!--- End grid -->

<!--- ---------------------------------------------------------------------- -->
<!--- 2.1a. Try some options for provider tiles -->

<div class="row"> <!--- Setup grid for layout -->
<div class="col-md-12"> <!--- Begin column set -->
<div class="panel panel-section"> <!--- Begin panel -->
<h3 id="2.1a">2.1a &nbsp; Load libraries and data, prepare for mapping</h3>
</div> <!--- End panel -->
</div> <!--- End column set -->
</div> <!--- End grid -->

Navigate to Day 2/worksheets, and copy <b>dat2_leaflet_intro.R</b> to create a personal version of this R script to edit. This script has some code to help you get started. There are various bits of code in here that we'll invite you to edit as we move through the slides together. Feel free to add in any code from the slides and to try out other functions in the packages we'll work with that we don't have time to cover.

Open your version and follow the code to load libraries and data required. Then, follow code to create to:
<br>1) create a new column/variable 'species type' (Human, Domestic or Wildlife)
<br>2) create ``map_data`` --- a dataframe consisting of 2014 data only

<!--- ---------------------------------------------------------------------- -->
<!--- 2.2 Build a leaflet map in R-->

<br>
<div class="row"> <!--- Setup grid for layout -->
<div class="col-md-12"> <!--- Begin column set -->
<div class="panel panel-aims"> <!--- Begin panel -->
<h3>2.2 &nbsp; Build a leaflet map in R</h3>
</div> <!--- End panel -->
</div> <!--- End column set -->
</div> <!--- End grid -->


<!--- ---------------------------------------------------------------------- -->
<!--- 2.2a. Try some options for provider tiles -->

<div class="row"> <!--- Setup grid for layout -->
<div class="col-md-12"> <!--- Begin column set -->
<div class="panel panel-section"> <!--- Begin panel -->
<h3 id="2.2a">2.2a &nbsp; Try some options for provider tiles</h3>
</div> <!--- End panel -->
</div> <!--- End column set -->
</div> <!--- End grid -->

Within your version of <b class="blue">day2_leaflet_intro.R</b>, initialise map using ``leaflet()`` with datapoints added using ``addCircles()``. Try some options for provider tiles using ``addProviderTiles(providers$___)``.

Hint: use tab completion to access list of options (some options require registration etc. so won't be instantly available).

<!--- ---------------------------------------------------------------------- -->
<!--- 2.2b. Add circles coloured by species with legend and scale bar -->

<div class="row"> <!--- Setup grid for layout -->
<div class="col-md-12"> <!--- Begin column set -->
<div class="panel panel-section"> <!--- Begin panel -->
<h3 id="2.2b">2.2b &nbsp; Add circles coloured by species with legend and scale bar</h3>
</div> <!--- End panel -->
</div> <!--- End column set -->
</div> <!--- End grid -->

Within your version of <b class="blue">day2_leaflet_intro.R</b>, navigate to *"Your turn 2.2b"* and adapt the example code.

The aim is to produce a map with:
<br>1) tiles showing topography
<br>2) circles coloured by species (instead of species type)
<br>3) a colour legend
<br>4) a scale bar showing distance in kilometers 

Hint: ?addScaleBar

<!--- ---------------------------------------------------------------------- -->
<!--- 2.2c. Colour points by density using a continuous colour scale -->

<div class="row"> <!--- Setup grid for layout -->
<div class="col-md-12"> <!--- Begin column set -->
<div class="panel panel-section"> <!--- Begin panel -->
<h3 id="2.2c">2.2c &nbsp; Colour points by density using a continuous colour scale</h3>
</div> <!--- End panel -->
</div> <!--- End column set -->
</div> <!--- End grid -->

Within your version of <b class="blue">day2_leaflet_intro.R</b>, navigate to *"Your turn 2.2c"* and adapt the example code.

Adapt the example code there to produce a map with:
<br>1) Circles coloured by population density using the viridis palette
<br>2) a legend and scale bar

<!--- ---------------------------------------------------------------------- -->
<!--- 2.2d. Build choropleth with circles for point data -->

<div class="row"> <!--- Setup grid for layout -->
<div class="col-md-12"> <!--- Begin column set -->
<div class="panel panel-section"> <!--- Begin panel -->
<h3 id="2.2d">2.2d &nbsp; Build choropleth with circles for point data</h3>
</div> <!--- End panel -->
</div> <!--- End column set -->
</div> <!--- End grid -->

Within your version of <b class="blue">day2_leaflet_intro.R</b>, navigate to *"Your turn 2.2d"* and adapt the example code.

The aim is to adapt the code for plotting a choropleth with:
<br>1) ``colorQuantile()`` instead of ``colorNumeric()`` for the choropleth
<br>2) and with circles coloured by date for human cases within ``map_data``.

Hint: to colour circles by date, create ``myPal2`` using ``colorNumeric()``

<!--- ---------------------------------------------------------------------- -->
<!--- 2.2e. Build map showing raster and shape data -->

<div class="row"> <!--- Setup grid for layout -->
<div class="col-md-12"> <!--- Begin column set -->
<div class="panel panel-section"> <!--- Begin panel -->
<h3 id="2.2e">2.2e &nbsp; Build map showing raster and shape data</h3>
</div> <!--- End panel -->
</div> <!--- End column set -->
</div> <!--- End grid -->

Within your version of <b class="blue">day2_leaflet_intro.R</b>, navigate to *"Your turn 2.2e"* and adapt the example code.

The aim is to produce a version of the map showing the raster data for human population density with an additional layer showing region borders. When the cursor hovers over a region on the map, labels should show up and the region's border should appear highlighted.

Hint: Could ``addPolygons()``'s ``fillOpacity =`` argument help visualisation of the raster layer?

<!--- ---------------------------------------------------------------------- -->
<!--- 2.3 Build an interactive map -->

<br>
<div class="row"> <!--- Setup grid for layout -->
<div class="col-md-12"> <!--- Begin column set -->
<div class="panel panel-aims"> <!--- Begin panel -->
<h3>2.3 &nbsp; Build an interactive map</h3>
</div> <!--- End panel -->
</div> <!--- End column set -->
</div> <!--- End grid -->


<!--- ---------------------------------------------------------------------- -->
<!--- 2.3a. Colouring points by a selected variable -->

<div class="row"> <!--- Setup grid for layout -->
<div class="col-md-12"> <!--- Begin column set -->
<div class="panel panel-section"> <!--- Begin panel -->
<h3 id="2.3a">2.3a &nbsp; Colouring points by a selected variable</h3>
</div> <!--- End panel -->
</div> <!--- End column set -->
</div> <!--- End grid -->

Please navigate to the <b class="blue">Apps/Day 2 - map_1</b> folder and open up the <b class="blue">ui.R</b> and <b class="blue">server.R</b> scripts in R Studio.
<br><br>
This is an app that displays a leaflet map with a background tile, the region shapefile, and the locations of our data points.
<br>
There is only 1 widget - ``selectInput()`` - to show a Dropdown menu that selects a variable by which the data points should be coloured.
<br><br>
Please take a moment to have a look at the server and ui scripts, then run the app.
<br><br>
<h4 class="blue">Questions: </h4>
<ol>
<li>What does the ``selected="species"`` argument in the ``selectInput()`` function do?</li>
<li>What differences do you see in the map legends displayed for species and date.  What is the reason for these differences?</li>
</ol>
<br>
<h4 class="blue">Activity: Add age and sex as options to colour the points by.</h4>
<br>
<em>
Hints:
<ul>
<li>You will need to change both files</li>
<li>Think about what type of variables age and sex are.  Are they factors or numeric?</li>
<li>The operators | or %in% will help you make the necessary changes to the server</li>
</ul>
</em>
<br>


<!--- ---------------------------------------------------------------------- -->
<!--- 2.3b. Displaying a subset of points using pickerInput -->

<div class="row"> <!--- Setup grid for layout -->
<div class="col-md-12"> <!--- Begin column set -->
<div class="panel panel-section"> <!--- Begin panel -->
<h3 id="2.3b">2.3b &nbsp; Displaying a subset of points using pickerInput</h3>
</div> <!--- End panel -->
</div> <!--- End column set -->
</div> <!--- End grid -->

Please navigate to the <b class="blue">Apps/Day 2 - map_2</b> folder and open up the <b class="blue">ui.R</b> and <b class="blue">server.R</b> scripts in R Studio.
<br><br>
This is the same map app as before, but with a new ``pickerInput`` menu for selecting which species to display on the map.
<br><br>
Please take a moment to have a look at the server and ui scripts, then run the app.  Try out the new ``pickerInput`` menu.
<br><br>
<h4 class="blue">Questions: </h4>
<ol>
<li>What other widgets could we have used to allow selection of the species to display?</li>
<li>When do you think the live-search and Select All/Deselect All abilities of ``pickerInput`` would be particularly useful?</li>
<li>In the previous version of the app, ``popUpInfo`` was created in the section above the server.  Why does it now need to be a ``reactive`` function within the server?</li>
</ol>
<br>
<h4 class="blue">Activity: Change the app so that ``pickerInput`` subsets the points based on region instead of species</h4>
<br>
<em>
Hint:
<ul>
<li>You will need to change both files</li>
</ul>
</em>
<br>



<!--- ---------------------------------------------------------------------- -->
<!--- 2.3c. Selectable map layers -->

<div class="row"> <!--- Setup grid for layout -->
<div class="col-md-12"> <!--- Begin column set -->
<div class="panel panel-section"> <!--- Begin panel -->
<h3 id="2.3c">2.3c &nbsp; Selectable map layers</h3>
</div> <!--- End panel -->
</div> <!--- End column set -->
</div> <!--- End grid -->

Please navigate to the <b class="blue">Apps/Day 2 - map_3</b> folder and open up the <b class="blue">ui.R</b> and <b class="blue">server.R</b> scripts in R Studio.
<br><br>
This map app has a new third widget; a checkbox that allows the user to select whether to display the region shapefile.
<br><br>
Please take a moment to have a look at the server and ui scripts, then run the app.  
<br><br>
<h4 class="blue">Questions: </h4>
Have a look at the ``checkboxInput()`` code.  Compare with the ``checkboxGroupInput()`` code from Day 1. 
<ol>
<li>What arguments do the two functions share?</li>  
<li>By which arguments do they differ?</li>
</ol>
<br>
<h4 class="blue">Activity: Change the ``checkboxInput`` widget to a ``checkboxGroupInput`` widget, with selectable region and protected areas shapefiles</h4>
<br>
<em>
Hints:
<ul>
<li>You will need to change both files</li>
<li>The protected areas shapefile can be found in the app's 'data' folder - you will need to read it into the server </li>
<li>Remember that the server input from ``checkboxGroupInput`` is a vector of choices, not a logical value</li>
<li>You will need to add an extra ``if()`` statement to the leaflet code</li>
</ul>
</em>
<br>



<!--- ---------------------------------------------------------------------- -->
<!--- 2.3d. Adding a slider to choose the date range of points -->

<div class="row"> <!--- Setup grid for layout -->
<div class="col-md-12"> <!--- Begin column set -->
<div class="panel panel-section"> <!--- Begin panel -->
<h3 id="2.3d">2.3d &nbsp; Adding a slider to choose the date range of points</h3>
</div> <!--- End panel -->
</div> <!--- End column set -->
</div> <!--- End grid -->


Please navigate to the <b class="blue">Apps/Day 2 - map_4</b> folder and open up the <b class="blue">ui.R</b> and <b class="blue">server.R</b> scripts in R Studio.
<br><br>
This map app includes all the features we have already developed.  
<br>
Now it's your turn to add a new widget!
<br><br>
<h4 class="blue">Activity: Add a ``sliderInput`` that subsets the points to a selected date range.</h4>
<br>
<em>
Hints:
<ul>
<li>You will need to change both files</li>
<li>You can use ``?sliderInput`` or your code from the Day 1 task 1.4f to help you identify the arguments needed by the ``sliderInput`` function</li>
<li>In the server, the points are already being subsetted by species - try adding your code for subsetting by date to the same section</li>
</ul>
</em>
<br>
