---
title: "Shiny Workshop: Day 2"
output: 
  html_document:
    theme: yeti
    highlight: tango

---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
```

<style>
h1, h2, h3, h4 {font-weight: bold;}
.question {font-weight: bold; color: #4E23B8;}
hr {border: 2px solid black;}
a:link {color: white; text-decoration: none;}
a:visited {color: white; text-decoration: none;}
a:hover {color: #c9bde9; text-decoration: none;}
a:active {color: white; text-decoration: none;}
.panel-aims {color: white; background-color: #4E23B8; border-top: 3px solid black; border-bottom: 3px solid black; padding-left: 15px; padding-right: 15px; } 
.panel-section {color: black; background-color: #c9bde9; border-top: 3px solid black; border-bottom: 3px solid black; padding-left: 15px; padding-right: 15px; } 
</style>

<!--- ---------------------------------------------------------------------- -->
<!--- Aims section -->

<br>
<div class="row"> <!--- Setup grid for layout -->
<div class="col-md-12"> <!--- Begin column set -->
<div class="panel panel-aims"> <!--- Begin panel -->
<h3>Aims</h3>
<ul>
<li><a href="#2.1">Review Day 1</a></li>
<li><a href="#2.2">Build a app with a map</a></li>
<li><a href="#2.3">Build an app with multiple tabs</a></li>
</ul>
<br>
If you'd like to view a specific section of the document, click on the aim above.  
</div> <!--- End panel -->
</div> <!--- End column set -->
</div> <!--- End grid -->

<!--- ---------------------------------------------------------------------- -->
<!--- 2.1. Review Day 1 -->

<div class="row"> <!--- Setup grid for layout -->
<div class="col-md-12"> <!--- Begin column set -->
<div class="panel panel-section"> <!--- Begin panel -->
<h3 id="2.1">2.1 &nbsp; Review Day 1</h3>
</div> <!--- End panel -->
</div> <!--- End column set -->
</div> <!--- End grid -->

<br>

<!--- ---------------------------------------------------------------------- -->
<!--- 2.2. Build a app with a map -->

<div class="row"> <!--- Setup grid for layout -->
<div class="col-md-12"> <!--- Begin column set -->
<div class="panel panel-section"> <!--- Begin panel -->
<h3 id="2.2">2.2 &nbsp; Build a app with a map</h3>
</div> <!--- End panel -->
</div> <!--- End column set -->
</div> <!--- End grid -->

<ul>
<li>Provide template for simple layout</li>
<li>Use point data as example in leaflet</li>
<li>If participants are doing well, give example with polygons</li>
</ul>
<br>

<!--- ---------------------------------------------------------------------- -->
<!--- 2.3. Build an app with multiple tabs -->

<div class="row"> <!--- Setup grid for layout -->
<div class="col-md-12"> <!--- Begin column set -->
<div class="panel panel-section"> <!--- Begin panel -->
<h3 id="2.3">2.3 &nbsp; Build an app with multiple tabs</h3>
</div> <!--- End panel -->
</div> <!--- End column set -->
</div> <!--- End grid -->

<ul>
<li>Provide template for tabbed layout</li>
<li>Combine code for plots from other apps OR if participant is doing well, create new plots</li>
</ul>
<br>
